-- Create raw matches table for ingested football data
CREATE TABLE IF NOT EXISTS raw_matches (
    id SERIAL PRIMARY KEY,
    division VARCHAR(10),
    season VARCHAR(10),
    match_date DATE,
    match_time VARCHAR(10),
    home_team VARCHAR(100),
    away_team VARCHAR(100),
    ft_home_goals INT,
    ft_away_goals INT,
    ft_result CHAR(1),
    ht_home_goals INT,
    ht_away_goals INT,
    ht_result CHAR(1),
    referee VARCHAR(100),
    home_shots INT,
    away_shots INT,
    home_shots_on_target INT,
    away_shots_on_target INT,
    home_fouls INT,
    away_fouls INT,
    home_corners INT,
    away_corners INT,
    home_yellows INT,
    away_yellows INT,
    home_reds INT,
    away_reds INT,
    UNIQUE(division, season, match_date, home_team, away_team)
);

-- Create team profiles table for transformed data
CREATE TABLE IF NOT EXISTS team_stats (
    id SERIAL PRIMARY KEY,
    season VARCHAR(10),
    division VARCHAR(10),
    team VARCHAR(100),
    matches_played INT,
    wins INT,
    draws INT,
    losses INT,
    goals_scored INT,
    goals_conceded INT,
    goal_difference INT,
    clean_sheets INT,
    avg_goals_scored NUMERIC(5,2),
    avg_goals_conceded NUMERIC(5,2),
    avg_shots NUMERIC(5,2),
    avg_shots_on_target NUMERIC(5,2),
    shot_accuracy NUMERIC(5,2),
    avg_corners NUMERIC(5,2),
    avg_fouls NUMERIC(5,2),
    avg_yellows NUMERIC(5,2),
    avg_reds NUMERIC(5,2),
    home_wins INT,
    home_draws INT,
    home_losses INT,
    away_wins INT,
    away_draws INT,
    away_losses INT,
    last5_wins INT,
    last5_draws INT,
    last5_losses INT,
    last5_goals_scored INT,
    last5_goals_conceded INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(season, division, team)
);
